language: bash

sudo: false

services:
  - docker

before_script:
  - make image no-cache=yes VERSION=test
  - make deps.bats

script:
  - make test VERSION=test

notifications:
  email:
    on_success: never
    on_failure: always
